Neos:
  Flow:
    mvc:
      flashMessages:
        containers:
          'Neos.Workspace.Ui:httpHeaderFlashMessages':
            storage: 'Neos\Workspace\Ui\Mvc\HttpHeaderFlashMessageStorage'
            requestPatterns:
              'htmx':
                pattern: 'Neos\Workspace\Ui\Mvc\HtmxRequestPattern'
                options:
                  matchingPackageKeys:
                    'Neos.Workspace.Ui': true
