Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        authProvider:
          factoryObjectName: Neos\ContentRepository\TestSuite\Fakes\FakeAuthProviderFactory
        clock:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeClockFactory'
        nodeTypeManager:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeNodeTypeManagerFactory'
        contentDimensionSource:
          factoryObjectName: 'Neos\ContentRepository\TestSuite\Fakes\FakeContentDimensionSourceFactory'
