Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        contentGraphProjection:
          factoryObjectName: Neos\ContentGraph\PostgreSQLAdapter\PostgresContentGraphProjectionFactory

